# Generated by Django 5.0.2 on 2024-04-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.PositiveIntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('field_of_study', models.CharField(max_length=50)),
                ('first_sem', models.FloatField()),
                ('second_sem', models.FloatField()),
                ('third_sem', models.FloatField()),
                ('reappear', models.CharField()),
                
            ],
        ),
    ]
