# Generated by Django 5.0.2 on 2024-04-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reappear',
            field=models.CharField(max_length=150),
        ),
    ]
